language: csharp
solution: intacct-sdk-net.sln
mono: none
dotnet: 2.0.0

notifications:
  slack:
    secure: beZMjb2AbOzhC4OOZvQz8so1QaJtrI0m1qQx3qW6+0/REjYxVPmkn3q/z5J0QLDVqv/Mq6wKB1koZKC9J3KDo59KhfsoyaU+HFPHqry9pf9YV5waEsDhC2hZoo8KSwEWbA1P6QfuXaJutw6wu6zGE2uiZoeggodh0/GTTnBJQJ7ljxHldWth/Co5skZSxrqjOHrb2kYUdYMOqJLu4e/y15jPwgspehGJXx7C5YOD5LNBBHs6geSriI8+t6WDXlDU40smth+H0zTe6rGCDRl+P3rajO5sZbrLldib8kQYizi5EtTrgLcqOuIL8g2fWTZEyQ6G/irFUhZW9uNkCGr+PWBdec0iU68sFThi9IixN+40yKJdlo+lLd/h55Sc3q/8/fK2DMY/yHiaFCcRBd2ZEavdL85Vfall94BHRGpXE6oR+iKg9OWGBTvFgrajroFRuySUQ/ks50pF0euwmk6WwLVGgOEpKgPwBEGeZYjbnBYeVXuqIAVmUMa/lvrWdyEjsdXv4HAxDp51eRdZa5mmWEwdQPu1PVLcNX/WXkgd/wvCWqpHdb3uINNvj/CrNPckrReAhlmn52x+G2qwJgott02j0tzI6Z0EXoE4mW+I4FfMUTTZWsWZVdICERQGoOXlfBya8JrHvbYHUDJxeqT763sziSmR32YTjzx273noxbQ=
